name: Bug Report
description: Create a bug report for Template. 🐛
body:
  - type: textarea
    attributes:
      label: Describe the bug …
      description: A detailed description of the bug and it's consequences.
    validations:
      required: true
  - type: input
    attributes:
      label: Which version of Template are you using?
      description: A software version, accessible via the about dialog
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Source
      description: How was Template installed?
      options:
        - Flathub
        - Other Flatpak Repository
        - Other Package Manager
        - Build locally
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: The output of Template running in the command line.
      render: shell
    validations:
      required: true
