name: Feature Request
description: Create a feature request for Template. 🔐
body:
  - type: textarea
    attributes:
      label: Describe the feature …
      description: A detailed description of the feature and it's benefit to users.
    validations:
      required: true
