blank_issues_enabled: false
contact_links:
  - name: Project Maintainer
    url: https://konstantintutsch.com/#contact
    about: Please feel free to ask any questions regarding your contributions here.
