name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flatpak:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Update package lists
      run: sudo apt-get update
  
    - name: Install build tools
      run: sudo apt-get install just meson flatpak flatpak-builder

    - name: Install build dependencies
      run: |
        sudo apt-get install libadwaita-1-dev
        sudo flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install --assumeyes org.gnome.Sdk//46 org.gnome.Platform//46

    - name: Build development profile
      run: just devel

    - name: Build release profile
      run: just release
